logging:
  level:
    com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false: DEBUG
    com.sap.cloud.sdk: INFO
    root: WARN

server:
  port: 8080
